# Generated by Django 5.1.6 on 2025-03-24 11:59

from django.db import migrations
from django.utils import timezone


def create_mock_posts(apps, schema_editor):
    Post = apps.get_model('posts', 'Post')
    User = apps.get_model('users', 'User')

    user1 = User.objects.get(username='user1')
    user2 = User.objects.get(username='user2')

    Post.objects.create(title='Post 1', content='Content 1', author=user1, created_at=timezone.now())
    Post.objects.create(title='Post 2', content='Content 2', author=user2, created_at=timezone.now())


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
        ('users', '0002_auto_20250324_1454'),
    ]

    operations = [
        migrations.RunPython(create_mock_posts),
    ]