# Generated by Django 5.1.6 on 2025-03-24 11:54

from django.db import migrations


def create_mock_users(apps, schema_editor):
    User = apps.get_model('users', 'User')
    User.objects.create(username='user1', first_name="Chel", last_name="")
    User.objects.create(username='user2', first_name="Mia", last_name="Kweent")


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_mock_users)
    ]