# Generated by Django 5.1.6 on 2025-03-24 19:09

from django.db import migrations


def create_mock_users(apps, schema_editor):
    User = apps.get_model('users', 'User')
    User.objects.create(username='admin1', first_name="User", last_name="Super", is_staff=True)


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_is_staff'),
    ]

    operations = [
        migrations.RunPython(create_mock_users),
    ]