# Generated by Django 5.1.6 on 2025-03-24 12:11

from django.db import migrations
from django.utils import timezone


def create_mock_comments(apps, schema_editor):
    Comment = apps.get_model('comments', 'Comment')
    User = apps.get_model('users', 'User')
    Post = apps.get_model('posts', 'Post')

    user1 = User.objects.get(username='user1')
    user2 = User.objects.get(username='user2')

    post1 = Post.objects.get(title='Post 1')
    post2 = Post.objects.get(title='Post 2')

    Comment.objects.create(post=post1, author=user1, text='Comment 1', created_at=timezone.now())
    Comment.objects.create(post=post1, author=user2, text='Comment 2', created_at=timezone.now())
    Comment.objects.create(post=post2, author=user1, text='Comment 3', created_at=timezone.now())


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
        ('users', '0002_auto_20250324_1454'),
        ('posts', '0002_auto_20250324_1459'),
    ]

    operations = [
        migrations.RunPython(create_mock_comments),
    ]